server:
  port: 8000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
mybatis-plus:
  mapper-locations: classpath*:org\afc\mappers\xml\*.xml